name: Calculator App CI/CD

on:
  push:
    branches:
      - staging
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./calculator

      - name: Run Tests
        run: |
          pytest
        working-directory: ./calculator

      - name: Build
        run: |
          # Add build steps if necessary
          echo "Build steps..."

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to Staging
        run: |
          # Add deployment steps to staging environment
          echo "Deploying to staging..."

  deploy_production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
      - name: Deploy to Production
        run: |
          # Add deployment steps to production environment
          echo "Deploying to production..."
