name: EC2 deployement

on: 
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps: 
    - name: checking-out code
      uses: actions/checkout@v4
      
    - name: looking into the runner machine
      run: ls

    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
           whoami
