name: Calculator App CI/CD

on:
  push:
    branches:
      - staging
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
