name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Install pytest for running tests

      - name: Run Tests
        run: |
          # Running tests

      - name: Build
        run: |
          # If there are any additional build steps for your Flask app, add them here
          echo "Building Application"

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Replace 'your-flask-app-directory' with the directory containing your Flask app
            cd flask.py
            # Restart the Flask app (replace 'app.py' with your actual app file)
            sudo systemctl restart flask.py
            echo "Deployed to Staging"

  deploy_production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Replace 'your-flask-app-directory' with the directory containing your Flask app
            cd flask.py
            # Restart the Flask app (replace 'app.py' with your actual app file)
            sudo systemctl restart flask.py
            echo "Deployed to Production"
